### ISSUE TITLE
[feature/no-ref/separate-rvo2] Construct AgentType and DeconflictionType structs

### ISSUE THREAD

**Issue by tashakim** [sisl/ConstructionBots.jl#48]
This is a first-step to a major refactoring effort.

mutable AgentType should include:
- Desired Velocity
- Alpha 
- Max Velocity
- ID
- Velocity

mutable DeconflictionType should enable:
- RVO
- Dispersion 
- Tangent Bug

**Comment by dylan-asmar** [comment]
I think we should construct the Deconfliction type as an `abstract type`

Something like (not sure on the exact name):

```julia
abstract type DeconflictionStrategy end
```

Then each algorithm would be a subtype of the abstract type:
```julia
struct RVO <: DeconflictionStrategy
    field_name_one::Float64
    field_name_two::Type
end
 ```

**Comment by tashakim** [comment]
Thanks Dylan, this sounds good to me.

**Comment by tashakim** [comment]
Restructuring effort is still underway, but @dylan-asmar please advise if there's a better file to define the new AgentType struct.

**Comment by tashakim** [comment]
`AgentType` schema is not final, and it should be consolidated according to which fields are being accessed and updated in common by deconfliction algorithms.

**Comment by tashakim** [comment]
Update: per offline sync, usage of AgentType should be deprecated.
Closing and moving to #50
