### ISSUE TITLE
[feature/no-ref/separate-rvo2] Extend Node to include fields from AgentType

### ISSUE THREAD

**Issue by tashakim** [sisl/ConstructionBots.jl#50]
Requirements:
- `velocity`, `desired_velocity`, `alpha` should be added to Node type
- [Updated for clarity] Relevant fields should be directly accessed from the Node
- `AgentType` from #48 should be discarded

**Comment by dylan-asmar** [comment]
Just a comment here for clarity. I don't think we need to pass nodes around as they are contained in the trees already.

**Comment by tashakim** [comment]
Thanks for the comment Dylan. To confirm, the Node type we discussed in this context is the `SceneNode`?

**Comment by tashakim** [comment]
Or perhaps this is a more suitable addition for `EntityGo`?

**Comment by dylan-asmar** [comment]
`TransportUnitGo` and `RobotGo` are subtypes of the abstract type `EntityGo` which is a subtype of the abstract type  `ConstructionPredicate`. `ConstructionPredicatd` are the node types of the construction schedule graph.

**Comment by tashakim** [comment]
This is mostly a design choice so I'm happy to consider other ideas here. I think it makes sense to extend the concrete types `RobotGo` and `TransportUnitGo` with the aforementioned fields i.e. alpha, desired twist for now. IIRC this aligns with our discussion last week, but let me know if you're thinking of a different direction.

**Comment by dylan-asmar** [comment]
I agree! I was just commenting on the phrasing of "passing nodes around". Sorry for any confusion.

**Comment by tashakim** [comment]
Great, thanks for the clarification!

**Comment by tashakim** [comment]
Updated original thread for clarity
