### ISSUE TITLE
[feature/no-ref/separate-rvo2] Create implementation files for deconfliction algos

### ISSUE THREAD

**Issue by tashakim** [sisl/ConstructionBots.jl#55]
Separate files should be created for each deconfliction algorithm type. Each file must contain a (i) concrete sub-type containing relevant variables, and an (ii) implementation of n_compute_twist(DeconflictionType, param_set) where param_set contains necessary fields to update twist: `alpha`, `desired_twist`, etc. 

A user may implement a custom algorithm using the template. See required components below:
- **deconfliction_interface.jl**: abstract DeconflictionType, n_compute_twist(DeconflictionType, p)
- **reciprocal_velocity_obstacle.jl**: struct ReciprocalVelocityObstacle <: DeconflictionType, impl of n_compute_twist(ReciprocalVelocityObstacle, p)
- **tangent_bug_policy.jl**: struct TangentBugPolicy <: DeconflictionType, impl of n_compute_twist(TangentBugPolicy, p)
...
- **deconfliction_template.jl**: struct CustomPolicy <: DeconflictionType, impl of n_compute_twist(CustomPolicy, p)

where p is `param_set`.

**Comment by dylan-asmar** [comment]
I think we should come up with a better than `n_compute_twist`. I know I wrote that on the board when we were talking, but I don't think its a good name. 

Ideas? Perhaps, `perform_deconfliction` or `update_twists`? I'm not a huge fan of either of these either though.

**Comment by tashakim** [comment]
I think that's a great idea. How about these: `deconflict_twists`, `perform_twists_deconfliction`, `resolve_twists_deconfliction`? Happy to go with your suggestions here Dylan.

**Comment by dylan-asmar** [comment]
I think I like `perform_twist_deconfliction`

**Comment by tashakim** [comment]
That sounds good to me as well
